/** Contract §4 — 安定エラーコード（S1 最小セット） */
export const ERROR_CODES = {
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  MODE_NOT_ALLOWED: 'MODE_NOT_ALLOWED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_DUPLICATE_ID: 'RESOURCE_DUPLICATE_ID',
  RELATION_NOT_FOUND: 'RELATION_NOT_FOUND',
  RELATION_DUPLICATE: 'RELATION_DUPLICATE',
  RELATION_INVALID: 'RELATION_INVALID',
  RESOURCE_INVALID_LIFECYCLE: 'RESOURCE_INVALID_LIFECYCLE',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  AI_CAPABILITY_NOT_SUPPORTED: 'AI_CAPABILITY_NOT_SUPPORTED',
  PLUGIN_NOT_FOUND: 'PLUGIN_NOT_FOUND',
  PLUGIN_VALIDATION_FAILED: 'PLUGIN_VALIDATION_FAILED',
  PLUGIN_INCOMPATIBLE_VERSION: 'PLUGIN_INCOMPATIBLE_VERSION',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const HTTP_STATUS_BY_ERROR: Record<ErrorCode, number> = {
  VALIDATION_REQUIRED_FIELD: 400,
  AUTH_INVALID_TOKEN: 401,
  AUTH_INVALID_CREDENTIALS: 401,
  MODE_NOT_ALLOWED: 403,
  RESOURCE_NOT_FOUND: 404,
  RESOURCE_DUPLICATE_ID: 409,
  RELATION_NOT_FOUND: 404,
  RELATION_DUPLICATE: 409,
  RELATION_INVALID: 422,
  RESOURCE_INVALID_LIFECYCLE: 422,
  FEATURE_DISABLED: 403,
  AI_PROVIDER_UNAVAILABLE: 503,
  AI_CAPABILITY_NOT_SUPPORTED: 422,
  PLUGIN_NOT_FOUND: 404,
  PLUGIN_VALIDATION_FAILED: 422,
  PLUGIN_INCOMPATIBLE_VERSION: 422,
  INTERNAL_ERROR: 500,
};
